### ISSUE TITLE
Firstchild menu tokens

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat10-profile#100]
The [menu_firstchild module](https://www.drupal.org/project/menu_firstchild) is used in Web Express in order to create a menu item that will redirect users to the first child page of that menu item.

There's a Drupal 10 compatible version of this that we should get installed otherwise we'll have lots of sites with menu items that don't work properly.

**Comment by jcsparks** [comment]
Looks like we missed enabling this module last week on the sandboxes last week.  Should be enabled and working now.
