### ISSUE TITLE
Architects done have permissions for social media blocks

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat10-profile#150]
Kevin helped me create a social media block for the new chancellor site and sent me the link of https://live-ucbdev-chancellor.pantheonsite.io/block/add/social_media_icons. When I click on that, I'm told I'm not authorized to access this page and my access is denied.

**Comment by jcsparks** [comment]
Hey @asvensen - Tim is going to fix the permissions in the profile so we don't have this issue on any site, but I've modified the new Chancellor site so `Architects` will have permissions to use the Social Media blocks now.

**Comment by asvensen** [comment]
Thank you! I appreciate it.
