### ISSUE TITLE
Sitemaps aren't working on live sites

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/tiamat10-profile#178]
https://www.colorado.edu/chancellor/sitemap.xml responds with a blank page...

Network tab says : 

`Failed to load resource: the server responded with a status of 404 ()` : `/sitemap_generator/default/sitemap.xsl:1`

I suspect it should be trying to load /chancellor/sitemap_generator... but I didn't see any obvious place to set the configuration for this.

**Comment by patrickbrown-io** [comment]
Needs to be set in `simple_sitemap.settings.yml` , `base_url`

```
max_links: 2000
cron_generate: true
cron_generate_interval: 0
generate_duration: 10000
entities_per_queue_item: 50
remove_duplicates: true
skip_untranslated: true
xsl: true
base_url: <url>
default_variant: default
custom_links_include_images: false
disable_language_hreflang: false
hide_branding: false
excluded_languages: {  }
enabled_entity_types:
  - node
  - taxonomy_term
  - menu_link_content

```

@jcsparks @tirazel

**Comment by jcsparks** [comment]
per-site settings are being applied to site now.
