### ISSUE TITLE
Editing Site Users

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat10-profile#78]
Sites need to be able to manage their own users, without help from SRC staff.

Web Express 3.0 allows Site Owners and Access Managers to invite and edit other site users and add/remove roles as necessary.  The Role Delegation module (https://www.drupal.org/project/role_delegation) allows us to establish a role hierarchy so a given role can't edit OR assign any roles above it. For example, a Site Manager should not be able to edit Architects or Developers and should also not be able to assign those roles to other users.  Site Managers can edit other Site Managers and assign the Site Manager ole to other users.

Site Managers are the only site users that should be allowed to edit other users, unless we establish an additional role at a later time.

**Comment by timurtripp** [comment]
Moved issue to the profile (most permission-related issues end up here, easier to keep track of).
