### ISSUE TITLE
Users can't unpublish content

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat10-profile#94]
I'm not sure what permission this is tied to but it look like roles other than developers do not have the ability to unpublish nodes. I tested this with the administrator role today and ran into this issue.

**Comment by timurtripp** [comment]
@jacob-korf Hey Jacob, does this one also get resolved by pull request #92? If so you should add a reference by editing the pull request and move this to "In Review" in the project board.

**Comment by jacob-korf** [comment]
Updated for the project board and added into the pull request.
